spring:
  # 激活环境配置
  profiles:
    active: dev
  # 文件编码 UTF8
  mandatory-file-encoding: UTF-8
  mvc:
    # 解决Springfox路径匹配问题
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      # 关闭默认静态资源的映射规则
      add-mappings: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    default-property-inclusion: non_null
  freemarker:
    check-template-location: false
  servlet:
    multipart:
      # 单文件上传大小限制
      max-file-size: 100MB
      # 一次请求多个文件大小限制
      max-request-size: 100MB

mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true
    # 指定默认枚举类型的类型转换器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    # 开启/关闭 banner 打印
    banner: false
    db-config:
      # 逻辑删除（软删除）
      logic-delete-value: UNIX_TIMESTAMP()
      logic-not-delete-value: 0
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml