server:
  port: 8080

spring:
  # 文件编码 UTF8
  mandatory-file-encoding: UTF-8
  mvc:
    # 解决Springfox路径匹配问题
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  freemarker:
    check-template-location: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false

jwt:
  # 秘钥
  secret: spring-boot-learning-examples-jwt
  # 过期时间（秒）
  expires: 604800